---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
  - name: docdb-demo

run:
  path: documentdb-java-todo-app/ci/tasks/integration.sh
  args: [
    --input-dir, docdb-demo
  ]
