---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  CF_MANIFEST_HOST:

inputs:
  - name: docdb-demo
  - name: candidate-release
  - name: version

outputs:
  - name: prepare-integration

run:
  path: documentdb-java-todo-app/ci/tasks/prepare-integration.sh
  args: [
    --input-dir, candidate-release,
    --output-dir, prepare-integration,
    --version-file, version/number,
    --input-manifest, documentdb-java-todo-app/manifest.yml,
    --artifactId, docdb-demo,
    --packaging, war
  ]
