---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

inputs:
  - name: docdb-demo

run:
  path: docdb-demo/ci/tasks/unit.sh
  args: [
    --input-dir, docdb-demo
  ]
